export interface EditorTheme {
  id: string
  name: string
  // Canvas
  canvasBg: string
  gridLine: string
  roomFill: string
  wallStroke: string
  wallWidth: number
  disabledFill: string
  disabledOpacity: number
  dragRectFill: string
  dragRectStroke: string
  labelColor: string
  selectionStroke: string
  // Panel
  panelBg: string
  panelBorder: string
  panelHeaderBg: string
  panelText: string
  panelTextMuted: string
  categoryBg: string
  categoryBorder: string
  entryBg: string
  entryActiveBg: string
  entryActiveBorder: string
  toolbarBg: string
  toolBtnBg: string
  toolBtnColor: string
  toolBtnActiveBg: string
  toolBtnActiveColor: string
  toolBtnActiveBorder: string
  btnBg: string
  btnColor: string
  btnBorder: string
  deleteBtnBg: string
  rotateBtnBg: string
}

export const THEMES: Record<string, EditorTheme> = {
  dark: {
    id: 'dark',
    name: 'Dark',
    canvasBg: '#1a1a2e',
    gridLine: '#333',
    roomFill: '#2a2a3e',
    wallStroke: '#c8b06b',
    wallWidth: 3,
    disabledFill: '#000',
    disabledOpacity: 0.5,
    dragRectFill: '#3498db',
    dragRectStroke: '#3498db',
    labelColor: '#666',
    selectionStroke: '#fff',
    panelBg: '#16213e',
    panelBorder: '#333',
    panelHeaderBg: '#16213e',
    panelText: '#ccc',
    panelTextMuted: '#666',
    categoryBg: 'transparent',
    categoryBorder: '#222',
    entryBg: '#1a2540',
    entryActiveBg: '#1a3050',
    entryActiveBorder: '#3498db',
    toolbarBg: '#16213e',
    toolBtnBg: '#1a2540',
    toolBtnColor: '#999',
    toolBtnActiveBg: '#2a4a6b',
    toolBtnActiveColor: '#eee',
    toolBtnActiveBorder: '#3498db',
    btnBg: '#333',
    btnColor: '#eee',
    btnBorder: '#333',
    deleteBtnBg: '#6b1a1a',
    rotateBtnBg: '#2a4a6b',
  },
  parchment: {
    id: 'parchment',
    name: 'Parchment',
    canvasBg: '#d4c5a0',
    gridLine: '#b8a97a',
    roomFill: '#c9b888',
    wallStroke: '#4a3520',
    wallWidth: 3,
    disabledFill: '#6b5b3a',
    disabledOpacity: 0.5,
    dragRectFill: '#8b6914',
    dragRectStroke: '#8b6914',
    labelColor: '#7a6b4a',
    selectionStroke: '#e74c3c',
    panelBg: '#e8dcc0',
    panelBorder: '#c4b490',
    panelHeaderBg: '#e8dcc0',
    panelText: '#3a2e1e',
    panelTextMuted: '#8a7a5a',
    categoryBg: 'transparent',
    categoryBorder: '#c4b490',
    entryBg: '#ddd0b0',
    entryActiveBg: '#c8b888',
    entryActiveBorder: '#8b6914',
    toolbarBg: '#e8dcc0',
    toolBtnBg: '#ddd0b0',
    toolBtnColor: '#6a5a3a',
    toolBtnActiveBg: '#8b6914',
    toolBtnActiveColor: '#fff',
    toolBtnActiveBorder: '#6b5010',
    btnBg: '#c4b490',
    btnColor: '#3a2e1e',
    btnBorder: '#b0a070',
    deleteBtnBg: '#a03030',
    rotateBtnBg: '#8b6914',
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    canvasBg: '#3a3a3a',
    gridLine: '#4a4a4a',
    roomFill: '#454545',
    wallStroke: '#c8b06b',
    wallWidth: 3,
    disabledFill: '#1a1a1a',
    disabledOpacity: 0.5,
    dragRectFill: '#c8b06b',
    dragRectStroke: '#c8b06b',
    labelColor: '#777',
    selectionStroke: '#c8b06b',
    panelBg: '#2e2e2e',
    panelBorder: '#4a4a4a',
    panelHeaderBg: '#2e2e2e',
    panelText: '#c0c0c0',
    panelTextMuted: '#777',
    categoryBg: 'transparent',
    categoryBorder: '#3a3a3a',
    entryBg: '#353535',
    entryActiveBg: '#444',
    entryActiveBorder: '#c8b06b',
    toolbarBg: '#2e2e2e',
    toolBtnBg: '#353535',
    toolBtnColor: '#999',
    toolBtnActiveBg: '#555',
    toolBtnActiveColor: '#c8b06b',
    toolBtnActiveBorder: '#c8b06b',
    btnBg: '#4a4a4a',
    btnColor: '#ddd',
    btnBorder: '#555',
    deleteBtnBg: '#6b2020',
    rotateBtnBg: '#555',
  },
  light: {
    id: 'light',
    name: 'Light',
    canvasBg: '#f0f0f0',
    gridLine: '#d0d0d0',
    roomFill: '#e4e4e4',
    wallStroke: '#333',
    wallWidth: 3,
    disabledFill: '#999',
    disabledOpacity: 0.4,
    dragRectFill: '#3498db',
    dragRectStroke: '#3498db',
    labelColor: '#888',
    selectionStroke: '#e74c3c',
    panelBg: '#fff',
    panelBorder: '#ddd',
    panelHeaderBg: '#fff',
    panelText: '#333',
    panelTextMuted: '#999',
    categoryBg: 'transparent',
    categoryBorder: '#eee',
    entryBg: '#f5f5f5',
    entryActiveBg: '#e0edff',
    entryActiveBorder: '#3498db',
    toolbarBg: '#fff',
    toolBtnBg: '#f0f0f0',
    toolBtnColor: '#666',
    toolBtnActiveBg: '#3498db',
    toolBtnActiveColor: '#fff',
    toolBtnActiveBorder: '#2980b9',
    btnBg: '#e0e0e0',
    btnColor: '#333',
    btnBorder: '#ccc',
    deleteBtnBg: '#e74c3c',
    rotateBtnBg: '#3498db',
  },
}

export const DEFAULT_THEME = THEMES.stone
